name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenSSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Set the PUBLIC_KEY environment variable for subsequent steps
      - name: Set PUBLIC_KEY environment variable
        run: echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> $GITHUB_ENV
        shell: bash

      # Ensure OPENSSH secret is passed correctly to the prebuild script
      - name: Run prebuild script to inject the publicKey into environment.prod.ts
        run: echo "OPENSSH=${{ secrets.OPENSSH }}" >> $GITHUB_ENV && echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> $GITHUB_ENV && npm run prebuild
        shell: bash

      # Build the Docker image using the PUBLIC_KEY environment variable
      - name: Build the Docker image
        run: docker build --build-arg PUBLIC_KEY=${{ secrets.PUBLIC_KEY }} -t your-image-name .
