name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenSSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Ensure ts-node is available for running the prebuild script
      - name: Install ts-node and TypeScript
        run: npm install ts-node typescript --save-dev

      # Run prebuild script to inject the publicKey into environment.prod.ts
      - name: Run prebuild script to inject the publicKey into environment.prod.ts
        env:
          OPENSSH: ${{ secrets.OPENSSH }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        run: npm run prebuild

      # Build the Docker image using the PUBLIC_KEY environment variable
      - name: Build the Docker image
        env:
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        run: docker build --build-arg PUBLIC_KEY=${{ secrets.PUBLIC_KEY }} -t your-image-name .
