name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Pass the PUBLIC_KEY secret directly into the prebuild step
      - name: Run prebuild script to inject the publicKey into environment.prod.ts
        run: PUBLIC_KEY=${{ secrets.PUBLIC_KEY }} npm run prebuild

      # Build the Docker image using the PUBLIC_KEY secret directly
      - name: Build the Docker image
        run: docker build --build-arg PUBLIC_KEY=${{ secrets.PUBLIC_KEY }} -t your-image-name .
