name: Build and Deploy Angular with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.cache/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          docker build \
            --build-arg PUBLIC_KEY="${{ secrets.PUBLIC_KEY }}" \
            -t your-image-name .

      - name: Push Docker image to Docker Hub
        run: |
          docker push your-image-name