name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Set the PUBLIC_KEY environment variable
        run: echo "PUBLIC_KEY=${{ secrets.PUBLIC_KEY }}" >> $GITHUB_ENV

      - name: Run prebuild script to inject the publicKey
        run: npm run prebuild

      - name: Build the Docker image
        run: |
          docker build --build-arg PUBLIC_KEY=${{ secrets.PUBLIC_KEY }} -t your-image-name .